[package]
name = "logger"
version = "0.1.0"
authors = ["lWX811995 <liaoguangming2@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
